"""init db

Revision ID: 4db9b01ff7d4
Revises: 
Create Date: 2022-03-29 16:01:33.381839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db9b01ff7d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('ctime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('mtime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('is_alive', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster')
    # ### end Alembic commands ###
